version: '3.1'

services:
  postgres:
    image: postgres:11.4-alpine
    networks:
      - db_int_network
    volumes:
      - psql_db_data:/var/lib/postgresql/data
    secrets:
      - psql-pw
      - psql-user
      - psql-db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
      POSTGRES_USER_FILE: /run/secrets/psql-user
      POSTGRES_DB_FILE: /run/secrets/psql-db
    restart: always

  apache:
    build:
      context: ./apache
      args:
        git_user_name: 'docker_user'
        git_user_email: 'example@email.com'
    image: apache_for_django
    networks:
      - db_int_network
      - nginx_ext_network
      - smtp_int_network
      - redis_int_network
    volumes:
      - ./django:/var/www/html/django_project/django
      - static_folder:/var/www/static
    secrets:
      - psql-pw
      - psql-user
      - psql-db
      - django-sk
      - django-eh
      - django-ehu
      - django-ehp
    environment:
      HOST_IP: $HOST_IP
      HOST_NAME: $HOST_NAME
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
      POSTGRES_USER_FILE: /run/secrets/psql-user
      POSTGRES_DB_FILE: /run/secrets/psql-db
      DJANGO_SK_FILE: /run/secrets/django-sk
      DJANGO_EH_FILE: /run/secrets/django-eh
      DJANGO_EHU_FILE: /run/secrets/django-ehu
      DJANGO_EHP_FILE: /run/secrets/django-ehp
    restart: always
    depends_on:
      - postgres
      - smtp
      - redis

  nginx:
    build: ./nginx
    image: nginx_for_apache
    environment:
      HOST_IP: $HOST_IP
      HOST_NAME: $HOST_NAME
    networks:
      - nginx_ext_network
    ports:
      - "80:80"
    volumes:
      - static_folder:/usr/share/nginx/html/static
      - media_folder:/usr/share/nginx/html/media
    depends_on:
      - apache

  smtp:
    image: namshi/smtp:latest
    networks:
      - smtp_int_network
    restart: always
    # default port - 25    

  redis:
    image: redis:5.0.5
    networks:
       - redis_int_network
    restart: always

networks:
  nginx_ext_network:
  db_int_network:
    internal: true
  smtp_int_network:
    internal: true
  redis_int_network:
    internal: true

volumes:
  psql_db_data:
  static_folder:
  media_folder:

secrets:
  psql-pw:
    file : secrets/psql-pw
  psql-user:
    file : secrets/psql-user
  psql-db:
    file : secrets/psql-db
  django-sk:
    file : secrets/django-sk
  django-eh:
    file : secrets/django-eh
  django-ehu:
    file : secrets/django-ehu
  django-ehp:
    file : secrets/django-ehp
